// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hott.API.EF;

#nullable disable

namespace hott.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("hott.API.Data.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("BuiltYear")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dates")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nights")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OutboundDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("RoomsCount")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Hotel");
                });

            modelBuilder.Entity("hott.API.Data.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("hott.API.Data.Models.Hotel", b =>
                {
                    b.OwnsOne("hott.API.Data.Models.Filters", "Amenities", b1 =>
                        {
                            b1.Property<int>("HotelId")
                                .HasColumnType("int");

                            b1.Property<bool>("AirConditioner")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Heating")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("MiniBar")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Phone")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Shower")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Slippers")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Tv")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Wifi")
                                .HasColumnType("tinyint(1)");

                            b1.HasKey("HotelId");

                            b1.ToTable("Hotel");

                            b1.WithOwner()
                                .HasForeignKey("HotelId");
                        });

                    b.OwnsOne("hott.API.Data.Models.Meals", "Meals", b1 =>
                        {
                            b1.Property<int>("HotelId")
                                .HasColumnType("int");

                            b1.Property<bool>("Breakfast")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Dinner")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Lunch")
                                .HasColumnType("tinyint(1)");

                            b1.HasKey("HotelId");

                            b1.ToTable("Hotel");

                            b1.WithOwner()
                                .HasForeignKey("HotelId");
                        });

                    b.OwnsOne("hott.API.Data.Models.Tourists", "Tourists", b1 =>
                        {
                            b1.Property<int>("HotelId")
                                .HasColumnType("int");

                            b1.Property<int>("Adults")
                                .HasColumnType("int");

                            b1.Property<int>("Childrens")
                                .HasColumnType("int");

                            b1.HasKey("HotelId");

                            b1.ToTable("Hotel");

                            b1.WithOwner()
                                .HasForeignKey("HotelId");
                        });

                    b.Navigation("Amenities")
                        .IsRequired();

                    b.Navigation("Meals")
                        .IsRequired();

                    b.Navigation("Tourists")
                        .IsRequired();
                });

            modelBuilder.Entity("hott.API.Data.Tour", b =>
                {
                    b.HasOne("hott.API.Data.Models.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });
#pragma warning restore 612, 618
        }
    }
}
